import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { useAuth } from '../contexts/AuthContext'
import './ReportsPage.css'

const money = new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' })
const nameOf = (student) => [student?.first_names, student?.paternal_surname, student?.maternal_surname].filter(Boolean).join(' ')
const attendanceNames = { present: 'Presente', absent: 'Ausente', late: 'Retardo', excused: 'Justificado' }

function downloadCsv(fileName, headers, rows) {
  const escape = (value) => `"${String(value ?? '').replaceAll('"', '""')}"`
  const csv = `\uFEFF${headers.map(escape).join(',')}\n${rows.map(row => row.map(escape).join(',')).join('\n')}`
  const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); const link = document.createElement('a'); link.href = url; link.download = fileName; link.click(); URL.revokeObjectURL(url)
}

export default function ReportsPage() {
  const { roles } = useAuth(); const [enrollments, setEnrollments] = useState([]); const [attendance, setAttendance] = useState([]); const [charges, setCharges] = useState([]); const [payments, setPayments] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const canAcademic = roles.some(role => ['superadmin', 'administrator', 'school_control'].includes(role.code)); const canFinance = roles.some(role => ['superadmin', 'administrator', 'finance'].includes(role.code)); const defaultTab = canAcademic ? 'enrollments' : 'finance'; const [tab, setTab] = useState(defaultTab)
  async function load() { setLoading(true); const tasks = []; if (canAcademic) { tasks.push(supabase.from('student_enrollments').select('*, students(first_names,paternal_surname,maternal_surname,enrollment_number,status), school_years(name), grades(name,education_levels(name)), school_groups!student_enrollments_group_id_grade_id_fkey(name)').order('created_at',{ascending:false})); tasks.push(supabase.from('attendance_records').select('*, students(first_names,paternal_surname,maternal_surname), attendance_sessions(attendance_date,school_groups(name))').order('recorded_at',{ascending:false})); } if (canFinance) { tasks.push(supabase.from('student_charges').select('*, students(first_names,paternal_surname,maternal_surname), billing_concepts(name)').order('due_date',{ascending:false})); tasks.push(supabase.from('payments').select('*, students(first_names,paternal_surname,maternal_surname), student_charges(billing_concepts(name))').order('paid_on',{ascending:false})); } const results = await Promise.all(tasks); const issue = results.map(result => result.error).find(Boolean); if(issue) setError(issue.message); else { let i=0; if(canAcademic){setEnrollments(results[i++].data);setAttendance(results[i++].data)}if(canFinance){setCharges(results[i++].data);setPayments(results[i++].data)} } setLoading(false) }
  useEffect(() => { void load() }, [])
  const attendanceSummary = useMemo(() => Object.entries(attendance.reduce((all, item) => ({ ...all, [item.status]: (all[item.status] || 0) + 1 }), {})), [attendance])
  const financial = useMemo(() => ({ charged: charges.reduce((sum,item)=>sum+Number(item.amount)-Number(item.discount_amount)+Number(item.surcharge_amount),0), collected: payments.reduce((sum,item)=>sum+Number(item.amount),0), balance: charges.reduce((sum,item)=>sum+Number(item.amount)-Number(item.discount_amount)+Number(item.surcharge_amount)-Number(item.paid_amount),0) }),[charges,payments])
  if(loading)return <main className="centered">Generando reportes…</main>
  return <><section className="page-heading report-title"><div><p className="eyebrow">Fase 11</p><h2>Reportes y exportaciones</h2><p>Descarga CSV compatible con Excel o utiliza imprimir para guardarlo como PDF.</p></div><button className="print-button" onClick={()=>window.print()}>Imprimir / Guardar PDF</button></section>{error&&<p className="error banner">{error}</p>}<div className="module-tabs">{canAcademic&&<><button className={tab==='enrollments'?'tab active-tab':'tab'} onClick={()=>setTab('enrollments')}>Matrícula</button><button className={tab==='attendance'?'tab active-tab':'tab'} onClick={()=>setTab('attendance')}>Asistencia</button></>}{canFinance&&<button className={tab==='finance'?'tab active-tab':'tab'} onClick={()=>setTab('finance')}>Finanzas</button>}</div>
    {tab==='enrollments'&&canAcademic&&<section className="report-card"><header><div><h3>Matrícula e inscripciones</h3><p>{enrollments.length} inscripciones registradas</p></div><button onClick={()=>downloadCsv('reporte-matricula.csv',['Alumno','Matrícula','Ciclo','Nivel','Grado','Grupo','Estatus'],enrollments.map(item=>[nameOf(item.students),item.students?.enrollment_number,item.school_years?.name,item.grades?.education_levels?.name,item.grades?.name,item.school_groups?.name,item.status]))}>Exportar a Excel (CSV)</button></header><ReportTable headers={['Alumno','Matrícula','Ciclo','Grupo','Estatus']} rows={enrollments.map(item=>[nameOf(item.students),item.students?.enrollment_number,item.school_years?.name,`${item.grades?.name||''} ${item.school_groups?.name||''}`,item.status])}/></section>}
    {tab==='attendance'&&canAcademic&&<section className="report-card"><header><div><h3>Asistencia</h3><p>{attendance.length} registros consultados</p></div><button onClick={()=>downloadCsv('reporte-asistencia.csv',['Alumno','Fecha','Grupo','Estado','Notas'],attendance.map(item=>[nameOf(item.students),item.attendance_sessions?.attendance_date,item.attendance_sessions?.school_groups?.name,attendanceNames[item.status],item.notes]))}>Exportar a Excel (CSV)</button></header><div className="report-kpis">{attendanceSummary.map(([status,count])=><article key={status}><span>{attendanceNames[status]}</span><strong>{count}</strong></article>)}</div><ReportTable headers={['Alumno','Fecha','Grupo','Estado']} rows={attendance.map(item=>[nameOf(item.students),item.attendance_sessions?.attendance_date,item.attendance_sessions?.school_groups?.name,attendanceNames[item.status]])}/></section>}
    {tab==='finance'&&canFinance&&<section className="report-card"><header><div><h3>Cartera y pagos</h3><p>Resumen financiero del sistema</p></div><button onClick={()=>downloadCsv('reporte-finanzas.csv',['Alumno','Concepto','Vencimiento','Total','Pagado','Saldo','Estatus'],charges.map(item=>[nameOf(item.students),item.billing_concepts?.name,item.due_date,Number(item.amount)-Number(item.discount_amount)+Number(item.surcharge_amount),item.paid_amount,Number(item.amount)-Number(item.discount_amount)+Number(item.surcharge_amount)-Number(item.paid_amount),item.status]))}>Exportar a Excel (CSV)</button></header><div className="report-kpis"><article><span>Cargos</span><strong>{money.format(financial.charged)}</strong></article><article><span>Cobrado</span><strong>{money.format(financial.collected)}</strong></article><article><span>Cartera pendiente</span><strong>{money.format(financial.balance)}</strong></article></div><ReportTable headers={['Alumno','Concepto','Vencimiento','Total','Pagado','Saldo']} rows={charges.map(item=>[nameOf(item.students),item.billing_concepts?.name,item.due_date,money.format(Number(item.amount)-Number(item.discount_amount)+Number(item.surcharge_amount)),money.format(item.paid_amount),money.format(Number(item.amount)-Number(item.discount_amount)+Number(item.surcharge_amount)-Number(item.paid_amount))])}/></section>}
  </>
}
function ReportTable({ headers, rows }) { return <div className="report-table-wrap"><table><thead><tr>{headers.map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,index)=><tr key={index}>{row.map((cell,i)=><td key={i}>{cell??'—'}</td>)}</tr>):<tr><td colSpan={headers.length}>No hay información para este reporte.</td></tr>}</tbody></table></div> }
